x-common-migration: &common-migration
  POSTGRES_HOST: ${POSTGRES_HOST:-ffc-demo-apply-postgres}
  SCHEMA_ROLE: ${POSTGRES_SCHEMA_ROLE:-postgres}
  SCHEMA_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
  SCHEMA_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
  SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}

x-common-postgres: &common-postgres
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_DB: ${POSTGRES_DB:-ffc_demo_apply}
  POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-ppp}
  POSTGRES_USER: ${POSTGRES_ADMIN_USERNAME:-postgres}

services:
  database-up:
    image: liquibase/liquibase:3.10.x
    environment:
      <<: [*common-migration, <<: *common-postgres]
    entrypoint: >
      sh -c "/scripts/migration/database-up"
    depends_on:
      - ffc-demo-apply-postgres
    volumes:
      - ./changelog:/liquibase/changelog
      - ./scripts:/scripts

  database-down:
    image: liquibase/liquibase:3.10.x
    environment:
      <<: [*common-migration, <<: *common-postgres]
    entrypoint: >
      sh -c "/scripts/migration/database-down"
    depends_on:
      - ffc-demo-apply-postgres
    volumes:
      - ./changelog:/liquibase/changelog
      - ./scripts:/scripts

  ffc-demo-apply-postgres:
    image: postgres:15.8-alpine3.20
    environment: *common-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
