version: '3.8'

services:
  ffc-demo-apply:
    build:
      context: .
      target: production
    image: ffc-demo-apply
    container_name: ffc-demo-apply
    depends_on:
      - ffc-demo-apply-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-apply-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      APPINSIGHTS_CONSOLE_DEBUG_ENABLED: ${APPINSIGHTS_CONSOLE_DEBUG_ENABLED:-false}
      APPLY_QUEUE_ADDRESS: ${APPLY_QUEUE_ADDRESS:-ffc-demo-apply}${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-ffc_demo_apply}
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-demo-apply-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  ffc-demo-apply-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_apply
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
