environment: development
environmentCode:
name: ffc-demo-apply
namespace: ffc-demo
workstream: ffc-demo
image: ffc-demo-apply

appInsights:
  connectionString:

labels: {}

containerConfigMap:
  name: ffc-demo-apply

containerSecret:
  name: ffc-demo-apply-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  imagePullSecret:

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 5Mi
  requestCpu: 5m
  limitMemory: 120Mi
  limitCpu: 120m
  applyQueueAddress: ffc-demo-apply
  messageQueueHost: myservicebus.servicebus.windows.net
  appInsightsConsoleDebugEnabled: true
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

postgresService:
  postgresDb: ffc_demo_apply
  postgresqlHost: ffc-demo-apply-postgres
  postgresSchema: public
  postgresUser: postgres
  postgresPort: 5432

workloadIdentity: true

# Enable if Managed Identity is required, ensure the clientID and resourceID are set in Platform Configuration
azureIdentity:
  resourceID: /subscriptions/cd4e9a00-99d8-45a2-98bb-7648ef12c26d/resourcegroups/SNDFFCAKSRG1001/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ffc-snd-demo-apply
  clientID: c1f67e8b-1da6-4213-b948-c312ffdb5058
