{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-apply.config-map") -}}
{{- define "ffc-demo-apply.config-map" -}}
data:
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  APPINSIGHTS_CONSOLE_DEBUG_ENABLED: {{ quote .Values.container.appInsightsConsoleDebugEnabled}}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  APPLY_QUEUE_ADDRESS: {{ quote .Values.container.applyQueueAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  APPLY_QUEUE_ADDRESS: {{ quote .Values.container.applyQueueAddress }}
  {{- end }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  NODE_ENV: {{ quote .Values.environment }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  APPINSIGHTS_CONSOLE_DEBUG_ENABLED: {{ quote .Values.container.appInsightsConsoleDebugEnabled}}
{{- end -}}
