environment: development
name: ffc-demo-apply
namespace: ffc-demo
workstream: ffc-demo
image: ffc-demo-apply

labels: {}

appInsights:
  key: 

azureIdentity:
  resourceID: not-a-real-resourceID
  clientID: not-a-real-clientID

containerConfigMap:
  name: ffc-demo-apply-config-map

containerSecret:
  name: ffc-demo-apply-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  imagePullSecret:

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 5Mi
  requestCpu: 5m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3003
  calculationQueueAddress: calculation
  claimQueueAddress: claim
  messageQueueHost: myservicebus.servicebus.windows.net
  scheduleTopicAddress: schedule
  appInsightsConsoleDebugEnabled: true
  notifyApiKey:
  notifyEmailTemplateKey:

postgresService:
  postgresDb: ffc_demo_apply
  postgresqlHost: ffc-demo-applys-postgres
  postgresSchema: public
  postgresUser: postgres
  postgresPort: 5432

livenessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true
