
environments:
  dev:
    dev01:
      image: hello-world
      command: ["bin/sh", "-c", "echo Hello World"]
      tests-path: "" 
      env-variables:
        env-url: dev01-demo-apply-web
        any-key: anyValue

    dev-integration:
      image: hello-world
      command: [""]
      tests-path: ""
      env-variables:
        env-url: devIntegration-demo-apply-web
        any-key: anyValue
        another-key: extra-value

  test:
    test-acceptance:
      image: hello-world
      command: [""]
      tests-path: ""
      env-variables:
        env-url: testAcceptance-demo-apply-web
        any-key: anyValue

    test-02:
      image: hello-world
      command: [""]
      tests-path: ""
      env-variables:
        env-url: test02-demo-apply-web
        any-key: anyValue