environments:
  dev:
    dev01:
      image: hello-world
      command: [""]
      tests_path: "test/"
      report_dir: "test-output/"
      env_variables:
        path: integration/
        env_url: dev01-demo-apply-web
        any_key: anyValue

    dev_integration:
      image: hello-world
      command: ["echo"]
      tests_path: "test/"
      report_dir: "test-output/"
      env_variables:
        path: integration/
        env_url: devIntegration-demo-apply-web
        any_key: anyValue
        anotherKey: extra-value

  test:
    test-acceptance:
      image: hello-world
      command: [""]
      tests_path: "test/"
      report_dir: "test-output/"
      env_variables:
        path: acceptance/
        env_url: testAcceptance-demo-apply-web
        any_key: anyValue

    test_02:
      image: hello-world
      command: [""]
      tests_path: "test/"
      report_dir: "test-output/"
      env_variables:
        path: acceptance/
        env_url: test02-demo-apply-web
        any_key: anyValue
        