environments:
  - name: dev
    environment_root_url: http://something
    image: docker_image
    path: acceptance/
  - name: test
    environment_root_url: http://something
    image: docker_image
    path: acceptance/
  
  