environments:
  dev:
    environment_root_url: http://something
    image: docker_image
    path: acceptance/
  test:
    environment_root_url: http://something
    image: docker_image
    path: acceptance/
  
  