{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-apply.config-map") -}}
{{- define "ffc-demo-apply.config-map" -}}
data:
  NODE_ENV: {{ .Values.environment | quote }}
  PORT: {{ .Values.container.port | quote }}
  APPINSIGHTS_CLOUDROLE: {{ .Chart.Name | quote }}
  APPINSIGHTS_CONSOLE_DEBUG_ENABLED: {{ .Values.container.appInsightsConsoleDebugEnabled | quote }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  APPLY_QUEUE_ADDRESS: {{ .Values.container.applyQueueAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  APPLY_QUEUE_ADDRESS: {{ quote .Values.container.applyQueueAddress }}
  {{- end }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  POSTGRES_DB: {{ .Values.postgresService.postgresDb | quote }}
  POSTGRES_HOST: {{ .Values.postgresService.postgresqlHost | quote }}
  POSTGRES_PORT: {{ .Values.postgresService.postgresPort | quote }}
  POSTGRES_SCHEMA_NAME: {{ .Values.postgresService.postgresSchema | quote }}
{{- end -}}
